# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O-1V5KviQVjmaUi6A1rEXYNEZiQMPMPl
"""

import datetime
import time
import os
import platform

def set_alarm(alarm_time):
    while True:
        current_time = datetime.datetime.now().strftime("%H:%M:%S")
        if current_time == alarm_time:
            print("Time to wake up!")
            play_alarm_sound()
            break
        time.sleep(1)

def play_alarm_sound():
    # Modify this function to play your preferred alarm sound.
    if platform.system() == "Darwin":
        os.system("afplay alarm.mp3")  # macOS
    elif platform.system() == "Linux":
        os.system("aplay alarm.wav")  # Linux
    elif platform.system() == "Windows":
        os.system("start alarm.mp3")  # Windows

def main():
    print("Simple Alarm Clock")
    print("Enter the time for your alarm (format: HH:MM:SS)")
    alarm_time = input(">> ")

    try:
        datetime.datetime.strptime(alarm_time, "%H:%M:%S")
    except ValueError:
        print("Invalid time format. Please use HH:MM:SS.")
        return

    current_time = datetime.datetime.now().strftime("%H:%M:%S")
    print(f"Current time is {current_time}. Alarm set for {alarm_time}.")

    set_alarm(alarm_time)

if __name__ == "__main__":
    main()